from __future__ import annotations

from typing import Protocol

from src.schemas.memory import MemoryPoint, MemorySearchRequest, MemoryWriteRequest


class MemoryStoreProtocol(Protocol):
    @property
    def backend(self) -> str: ...

    async def initialize(self) -> None: ...

    async def refresh_connection_status(self) -> str: ...

    async def write(self, request: MemoryWriteRequest) -> MemoryPoint | None: ...

    async def search(self, request: MemorySearchRequest) -> list[MemoryPoint]: ...

    async def list_points(self, request: MemorySearchRequest) -> list[MemoryPoint]: ...

    async def count_documents(self, request: MemorySearchRequest) -> int: ...
